blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls',namespace="post")),
    path('polls/',include('polls.urls',namespace="polls"),)
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    
]

blog/post/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name='post'
urlpatterns = [
    
    path('post/<slug:slug>/edit/', views.post_edit, name='post_edit'),
    path('post/<slug:slug>/detail/',views.post_detail,name='post_detail'),
    path('tag/<slug:tag_slug>/posts/',views.post_list,name='post_list_by_tag'),
    path('post/new/', views.post_new, name='post_new'),
    path('cat_post/<str:cats>/',views.cat_post,name='cat_post'),
    path('profile_edit/<int:id>/',views.profile_edit,name='profile_edit'),
    path('login/',auth_views.LoginView.as_view(template_name="registration/login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('sign_up/',views.sign_up,name='sign_up'),
    path('profile/',views.profile,name='profile'),
    path('category/',views.category,name='category'),
    path('', views.post_list, name='post_list'),
]

blog/post/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.text import slugify    #to slugify
from django.contrib.auth.models import User
from django.utils.html import mark_safe


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profiles',null=True)

    # def image_tag(self):
    #         return mark_safe('<img src="/media/%s" width="150" height="150" />' % (self.profile_pic))
            

    def __str__(self):  
        return str(self.user)

    def save(self, *args, **kwargs):
        try:
            this = Profile.objects.get(id=self.id)
            if this.profile_pic != self.profile_pic:
                this.profile_pic.delete(save=False)
        except:
            pass  # when new photo then we do nothing, normal case
        super().save(*args, **kwargs)
    



class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True,null=True)
    description = models.CharField(max_length=255,blank=True, null=True )
    parent = models.ForeignKey('self',on_delete=models.CASCADE,blank=True, null=True ,related_name='children')

    class Meta:
        unique_together = ('slug', 'parent',)    
        verbose_name_plural = "categories"     

    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(Category,self).save(*args,**kwargs)


    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=100)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(Tag,self).save(*args,**kwargs)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True,null=True)
    text = models.TextField()
    category = models.ForeignKey(Category,on_delete=models.CASCADE,default='',)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    tag = models.ManyToManyField(Tag,blank=True, related_name='tags')

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(Post,self).save(*args,**kwargs)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    parent = models.ForeignKey('self',on_delete=models.CASCADE,null=True, blank=True, related_name='replies')

    class Meta:
        ordering = ('created_date',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/post/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post,Category,Comment,Profile
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

    



class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email')





class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_pic',)



class UserProfileUpdateForm(forms.Form):
    first_name = forms.CharField(label='First Name',max_length=100)
    last_name = forms.CharField(label='Last Name',max_length=100)
    email = forms.EmailField(label='Email',max_length=100)
    profile_pic = forms.ImageField(label='Profile Pic')
    

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text','category')
      

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

blog/post/views.py
from django.shortcuts import render,get_object_or_404
from django.utils import timezone
from .models import Post,Category,Comment,Profile,Tag
from django.shortcuts import redirect
from .forms import PostForm, CommentForm,UserProfileForm,UserUpdateForm,UserCreateForm
#from taggit.models import Tag
from django.contrib.auth.models import User
#from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,authenticate
from django.contrib.auth.decorators import login_required
from blog.settings import BASE_DIR #to delete old profile pic
import os



# Create your views here.
def profile(request):
    username= request.user
    user = User.objects.get(username=username)
    try:
        pic = Profile.objects.get(user=user)
    except:
        profile = Profile(user=user,profile_pic=" ")
        
        profile.save()
        pic = profile.profile_pic
    return render(request,'post/profile.html',{'user':user,"pic":pic})

@login_required
def profile_edit(request,id):
    user = get_object_or_404(User,id=id)
    pic = get_object_or_404(Profile,user=user)
    
    p_form = UserProfileForm(request.POST,request.FILES,instance=pic)
    u_form = UserUpdateForm(request.POST,instance=user)
    if request.method == 'POST':
        
        if p_form.is_valid() and u_form.is_valid():
            """p_form.save(commit=False)
            if pic.profile_pic != None:
                p_form.profile_pic = p_form.cleaned_data.get('profile_pic')"""

            
            #os.remove(BASE_DIR+'\profiles'+pic.profile_pic.url)
            
            u_form.save()
            p_form.save()
            message = 'Your profile has been updated'
            return redirect('post:profile')
    else:
        print(user)
        p_form = UserProfileForm(instance=pic)
        u_form = UserUpdateForm(instance=user)
        return render(request,'post/profile_edit.html',{'p_form':p_form,'u_form':u_form})



def sign_up(request):
    form = UserCreateForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            
            user = form.save()

            login(request,user)
            
            return redirect('post:post_list')
    else:
        form = UserCreateForm()
        return render(request,'registration/sign_up.html',{'form':form})



def post_list(request,tag_slug=None):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date') 
    print(posts)
    if tag_slug :
        
        tag = Tag.objects.filter(slug=tag_slug).first()
        print(tag)
        query = tag_slug
        posts = Post.objects.filter(tag = tag).all()
        print(posts)
    return render(request, 'post/post_list.html', {"posts":posts})



def post_detail(request,slug):
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True,parent__isnull=True)
    new_comment = None 
    if request.method =='POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            parent_obj = None
            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            if parent_id:
                parent_obj = Comment.objects.get(id=parent_id)
                if parent_obj:
                    replay_comment = comment_form.save(commit=False)
                    replay_comment.parent = parent_obj


            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect("post:post_detail",slug=post.slug)
    else:
        comment_form = CommentForm()
    return render(request, 'post/post_detail.html', 
                    {'post': post,"comment_form":comment_form,'new_comment':new_comment,'comments':comments})




def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            #form.save_m2m()             #to save tags
            return redirect('post:post_detail',slug=post.slug)
    else:
        form = PostForm()
    return render(request, 'post/post_edit.html', {'form': form})


def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            #form.save_m2m()             #to save tags
            return redirect('post:post_detail', slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, 'post/post_edit.html', {'form': form})


def category(request):
    catg = Category.objects.all()
    return render(request,'post/catg.html',{'catg':catg})

def cat_post(request,cats):
    print(cats)
    category = Category.objects.filter(slug=cats ).first()
    print(category)
    posts = Post.objects.filter(category=category).all()
    print(posts)
    return render(request,'post/catg_post.html',{'posts':posts})

blog/post/templates/post/base.html
{% load static %}
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'post/post.css' %}">
    </head>
    <body>
        <div class="page-header">
            
            <h1><a href="/">Django Girls Blog</a></h1>
            <h1><a href="{% url 'polls:index' %}">Polls </a></h1>
            <h1><a href="{% url 'post:category' %}">Categories</a></h1>
            {% if user.is_authenticated %}
                <a href="{% url 'post:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <h1><a href="{% url 'post:profile' %}">Welcome {{ request.user }}</a></h1>
                <h3><a href="{% url 'post:logout' %}">Logout</a></h3>
            {% else %}
                <h3><a href="{% url 'post:login' %}">Login</a></h3>
                <h3><a href="{% url 'post:sign_up' %}">Signup</a></h3>
            {% endif %}
            
            
        </div>
        

        <div class="content container">
            <div class="row">
                <div class="col-md-8" >
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/post/templates/post/catg.html
{% extends 'post/base.html' %}

{% block content %}
    {% for cat in catg %}
        <div class="post">
            
            <h2><a href="{% url 'post:cat_post' cat.slug   %}">{{ cat.name }}</a></h2>
            
            {{ cat.description }}
            
        </div>
    {% endfor %}
{% endblock %}

blog/post/templates/post/catg_post.html
{% extends 'post/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
                {{ post.category }}
            </div>
            
            <h2><a href="{% url 'post:post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
            
            {{ post.text }}
            
        </div>
    {% endfor %}
{% endblock %}

blog/post/templates/post/post_detail.html
{% extends 'post/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'post:post_edit' slug=post.slug %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <p class="date">Tags: 
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'post:post_list_by_tag' tag.slug %}">
                    {{ tag.name|capfirst }}
                </a>
                 {% if not forloop.last %} , {% endif %}
            {% endfor %}
        </p>
        <h2>{{ post.title |capfirst }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
        
        {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment {{ total_comments|pluralize }}
        </h2>
        {% endwith %}

        {% for comment in comments %}
        <div class='comment'>
            <p class= 'info'>
                Comment {{ forloop.counter }} by {{ comment.name  }} {{ comment.created_date }}
            </p>
            {{ comment.body |linebreaksbr }}
            
            {% for reply in comment.replies.all %}
                <p class="info" style="color: brown;margin-top: 10px;margin-left: 20px;">
                    <strong>
                        {{ reply.name | capfirst }} | {{ reply.created }}
                    </strong>
                </p>
                <li style="color: brown;margin-top: 10px;margin-left: 20px;">{{ reply.body }}</li>
            {% endfor %}
            <h3>Reply</h3>
            <div style="margin-left: 20px;">
                <form action="." method="post">
                    {{ comment_form.as_p }}
                    {% csrf_token %}
                    <!-- Hidden input for parent comment.id-->
                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                    <input class="btn btn-primary" type="submit" value="Reply">
                </form>
            </div>
            
        </div>
        {% empty %}
        <p> There are no comments Yet.</p>
        {% endfor %}

        

        {% if new_comment %}
            <h2>Your Comment has been added </h2>
        {% else %}
        <h2>Add a new comment </h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value='Add comment'></p>
        </form>
        {% endif %}
    </div>
    
{% endblock %}

blog/post/templates/post/post_edit.html
{% extends 'post/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/post/templates/post/post_list.html
{% extends 'post/base.html' %}

{% block content %}
    {% if tag %}
        <h2>Post tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <div class="post" style="border:coral .2px solid;padding: 10px;" >
            <div class="date">
                {{ post.published_date }}
                Category: {{ post.category }}
                
                
               

            </div>
            Tags:
            {% for tag in post.tag.all %}
                <a href="{% url 'post:post_list_by_tag' tag.slug %}">
                    {{ tag.name|capfirst }}
                </a>
                 {% if not forloop.last %} , {% endif %}
            {% endfor %}
           
            
            <h2><a href="{% url 'post:post_detail' post.slug %}">{{ post.title |capfirst   }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/post/templates/post/profile.html
{% extends 'post/base.html' %}
{% load static %}

{% block content %}
<div class="post">
    <a class="btn btn-default" href="{% url 'post:profile_edit' user.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
    <h2>Username: {{ user.username }}</h2>
    <h2>Name: {{ user.first_name }} {{ user.last_name }}</h2>
    {% if not pic == 'None' %}
        <img src="{{ pic.profile_pic.url }}"  style="height: 250px;width: 300px;" alt="{{ pic }}">
    {% else %}
        <h2>Profile Pic: No Picture</h2>
    {% endif %}
    <h2>Email:{{ user.email }}</h2>
</div>



{% endblock %}

blog/post/templates/post/profile_edit.html
{% extends 'post/base.html' %}
{% load static %}

{% block content %}
{% if message %}
    {{ message }}
{% else %}
<div class="post">
    <form method="POST"  class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
       
        {{ u_form.as_p}}
        {{ p_form.as_p }}
        <button class="btn btn-primary" type="submit">Save</button>
  </form>
    
</div>
{% endif %}



{% endblock %}